### 배열 데이터를 효과적으로 다루는 NumPy

#### 배열 생성하기

In [2]:
!pip install numpy

In [2]:
import numpy as np

In [4]:
import numpy as np

data1 = [0,1,2,3,4,5]
a1 = np.array(data1)
print(a1)

[0 1 2 3 4 5]


In [7]:
data2 = [0.1,5,4,12,0.5]
a2 = np.array(data2)
print(a2)

[ 0.1  5.   4.  12.   0.5]


numpy.ndarray

In [11]:
data3 = [5,4,12,0.1,0.5]
a3 = np.array(data3)
a3

array([ 5. ,  4. , 12. ,  0.1,  0.5])

In [22]:
a = np.array([[1,2,3,], [4,5,6], [7,8,9]])
print(a)
print(a[1,1])
print(a[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
9


In [15]:
np.array([[0.5, 2, 0.01, 8],
         [0.1, 2.5, 5, 0.023, 8]])

array([list([0.5, 2, 0.01, 8]), list([0.1, 2.5, 5, 0.023, 8])],
      dtype=object)

#### 범위를 지정해 배열 생성

In [23]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [24]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [32]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [33]:
b1 = np.arange(12).reshape(4,3)
b1.shape

(4, 3)

In [2]:
b2 = np.arange(5)
b2.shape

(5,)

In [3]:
b2

array([0, 1, 2, 3, 4])

In [4]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [5]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

#### 특별한 형태의 배열 생성

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 배열의 데이터 타입 변환


In [10]:
np.array(['1.5','0.62','2','3.14','3.14592'])

array(['1.5', '0.62', '2', '3.14', '3.14592'], dtype='<U7')

In [98]:
str_a1 = np.array(['1.567', '0.123', '5.123' , '9', '8'])
num_a1 = str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [16]:
str_a1.dtype

dtype('<U5')

In [17]:
num_a1.dtype

dtype('float64')

In [18]:
str_a2 = np.array(['1','3','5','7','9'])
num_a2 = str_a2.astype(int)
num_a2

array([1, 3, 5, 7, 9])

In [19]:
str_a1.dtype

dtype('<U5')

In [20]:
num_a2.dtype

dtype('int32')

In [21]:
num_f1 = np.array([10, 21, 0.549, 4.75, 5.98])
num_i1 = num_f1.astype(int)
num_i1

array([10, 21,  0,  4,  5])

In [22]:
num_i1.dtype

dtype('int32')

#### 난수 배열의 생성

In [23]:
np.random.rand(2,3)

array([[0.52678248, 0.27593992, 0.79696649],
       [0.0914191 , 0.9164709 , 0.29173167]])

In [24]:
np.random.rand()

0.5719668645543359

In [25]:
np.random.rand(2,3,4)

array([[[0.74078694, 0.94728525, 0.60288291, 0.73534766],
        [0.48338311, 0.78390169, 0.76561388, 0.38868585],
        [0.41226906, 0.94661129, 0.44653326, 0.9923578 ]],

       [[0.3250582 , 0.48517515, 0.92001116, 0.73957164],
        [0.82236624, 0.35129722, 0.96541033, 0.12926708],
        [0.80426259, 0.63555528, 0.62906282, 0.57279817]]])

In [26]:
np.random.randint(10, size=(3,4))

array([[5, 1, 8, 8],
       [5, 3, 6, 1],
       [5, 2, 6, 2]])

In [31]:
np.random.randint(1, 30)

25

### 배열의 연산

#### 기본 연산

In [41]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])
arr3 = np.array([1.1,2.2,3.3,4.4])

In [33]:
arr1 + arr2

array([11, 22, 33, 44])

In [34]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [35]:
arr2 * 2

array([2, 4, 6, 8])

In [43]:
arr2 ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [37]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [38]:
arr1 / arr2

array([10., 10., 10., 10.])

In [44]:
arr1 / (arr2 ** 2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [45]:
arr1 > 20

array([False, False,  True,  True])

#### 통계를 위한 연산

In [46]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [47]:
[arr3.sum(), arr3.mean()]

[10, 2.0]

In [49]:
arr3.sum(), arr3.mean()

(10, 2.0)

In [48]:
[arr3.std(), arr3.var()]

[1.4142135623730951, 2.0]

In [51]:
arr3.min(), arr3.max()

(0, 4)

In [53]:
arr4 = np.arange(1,5)
arr4

array([1, 2, 3, 4])

In [54]:
arr4.cumsum()

array([ 1,  3,  6, 10], dtype=int32)

In [55]:
arr4.cumprod()

array([ 1,  2,  6, 24], dtype=int32)

#### 행렬 연산

In [62]:
A = np.array([0,1,2,3,]).reshape(2,2)

In [67]:
    B =  np.array([3,2,0,1]).reshape(2,2)
    B

array([[3, 2],
       [0, 1]])

In [68]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [69]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [74]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [75]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [76]:
    A.transpose()

array([[0, 2],
       [1, 3]])

In [81]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

### 배열의 인데싱과 슬라이싱

#### 배열의 인덱싱

In [83]:
a1 = np.array([0,10,20,30,40,50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [84]:
a1[0]

0

In [85]:
a1[4]

40

In [86]:
a1[5]

50

In [87]:
a1[5] = 70

In [88]:
a1

array([ 0, 10, 20, 30, 40, 70])

In [89]:
a1[[1,3,4]]

array([10, 30, 40])

In [90]:
a2 = np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [91]:
a2[0,2]

30

In [92]:
a2[2,2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [93]:
a2[1]

array([40, 50, 60])

In [94]:
a2[1] = np.array([45, 55, 65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [95]:
a2[1] = [47, 57, 67]

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

In [97]:
a2[[0,2], [0,1]]

array([10, 80])

In [3]:
a = np.array([1,2,3,4,5,6])
a[a > 3]


array([4, 5, 6])

In [4]:
a[(a % 2) == 0]

array([2, 4, 6])

In [7]:
b1 = np.array([0, 10 ,20 ,30 ,40 ,50])
b1[1:4]

array([10, 20, 30])

In [8]:
b1[:3]

array([ 0, 10, 20])

In [9]:
b1[2:]

array([20, 30, 40, 50])

In [10]:
b1[2:5] = np.array([25, 35, 45])
b1

array([ 0, 10, 25, 35, 45, 50])

In [12]:
b1[3:6] = 60
b1

array([ 0, 10, 25, 60, 60, 60])

In [13]:
b2 = np.arange(10, 100, 10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [14]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [15]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [16]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [17]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [18]:
b2[1][0:2]

array([40, 50])

In [20]:
b2[0:2, 1:3] = np.array([[25, 35], [55, 65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])

In [2]:
import pandas as pd
test_csv = pd.read_csv('C:/myPyCode/AL_11_D169_20200925.csv')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 0: invalid start byte